name: Deploy to LP NuxtHub
on: push

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if there are changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'apps/lp/**'
              - 'packages/types/**'
              - 'packages/utils/**'
              - 'package.json'
              - 'pnpm-lock.yaml'

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.src == 'true'
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./apps/lp

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          NUXT_PUBLIC_PAYLOAD_ID: ${{ secrets.NUXT_PUBLIC_PAYLOAD_ID }}

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: shelve-lp-s26a
          directory: ./apps/lp/dist
